### ISSUE TITLE
Would you recommend workflow-controller in production?

### ISSUE THREAD

**Issue by davidc-donorschoose** [AmadeusITGroup/workflow-controller#58]
How stable is this project? I found your project last year, shortly after it was written as a proof of concept for the Kubernetes project. There hasn't been a lot of activity since then, but I noticed some changes were merged today, so it's nice to know the project is maintained. 

I’m interested in using your workflow-controller to run the jobs in a simple batch cycle. I could easily describe our use case as a sequence of jobs (a jobTemplate list with dependencies to cause sequential execution) that would run once every night. We do upgrade our Kubernetes cluster fairly often, since we aren't in production yet. We are currently using Kubernetes-v1.9.5 on Docker-v17.03.2 (installed in AWS by Rancher-v1.6.16).

I would definitely be interested in two features:

(1) The cronworkflow in the most recent commit (Feb 4). I don’t see documentation or examples on that commit, so work may not be complete yet. It seems to implement what was described in https://github.com/AmadeusITGroup/workflow-controller/issues/29, which is still open.

(2) The “Docker multistage build” pull request (https://github.com/AmadeusITGroup/workflow-controller/pull/24) submitted last October. There are several changes in that commit, but I do like how it reworks the Makefile to containerize the golang compilation - with a particular golang docker image instead of a random Go SKD installed on a developer laptop.

**Comment by sdminonne** [comment]
@davidc-donorschoose , 

The project is maintained.
 There're some improvement that we're working on the most important are:

- #29 cronjob like functionalities: APIs have been committed but at the moment the controller is partially implemented but not committed. This is next big feature that will be implemented soon.
- A UI must be implemented, some work is done but we're far from something usable
- Some technical (for example #56, #35, and other like for example name generation)

About #24, I liked that PR (if I'm not wrong I stated it clearly) but the world of the container image is changing really fast. I'm not 100% sure we want to keep `docker build`. 
All the kubesphere is moving towards `bazel`  or something like `buildha` that's why we're reluctant to integrante it.

David, if I answered your questions please close this one, otherwise, don't hesitate to ask further.
